name: Docker

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    uses: Delemangi/.github/.github/workflows/docker.yaml@bebef88ed98bc1b3b43ed317e8fb9efae29427db
    secrets: inherit
