name: Linter

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tsc:
    uses: Delemangi/.github/.github/workflows/tsc.yaml@main
    secrets: inherit

  eslint:
    uses: Delemangi/.github/.github/workflows/eslint.yaml@main
    secrets: inherit

  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 24
      - run: npm ci --ignore-scripts
      - run: npm audit --audit-level=low
      - run: npm test
      - run: npm run build
